---
title: "NosAnalizamos.Rmd"
author: "Tomás"
date: "2026-05-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Carga de Librerias

```{r}
if (!require("pacman")) install.packages("pacman")

# Instalar todas las librerías necesarias
pacman::p_load(
  knitr,
  tidyverse,
  ggplot2,
  datasets,
  RColorBrewer,
  nycflights13,
  dplyr,
  dbplyr,
  tidyr,
  readr,
  car,
  GGally)
```

## Carga de los Datos

```{r}
# Empezamos por la linea 27 porque realmente los datos comienzan ahí
datos <- read_tsv("data/NosAutoanalizamos2026.tsv",
  skip = 27)

# Sabemos que R si no encuentra nombre para las columnas pone algo asi como "...1", por lo que eliminamos dichas columnas
datos <- datos %>%
  select(!starts_with("..."))
```

## Eliminar Usuario martsobm

```{r}
datos <- datos %>%
  filter(Id != "martsobm")
```

## Modificar Columnas de Notas

```{r}
notas <- datos %>%
  select("ALG", "ANM", "MD", "FP", "DCS") %>%
  mutate(
    across(
      everything(),
      ~ case_when(
        . == "NC" ~ 3,
        TRUE ~ as.numeric(gsub(",", ".", .))
      )))
```

## Tabla de Estadísticos

```{r}
estadisticos <- notas %>%
  summarise(across(everything(),
                   list(
                     min = ~ min(., na.rm = TRUE),
                    p25 = ~ quantile(., 0.25, na.rm = TRUE),
                    mediana = ~ median(., na.rm = TRUE),
                    media = ~ mean(., na.rm = TRUE),
                    sd = ~ sd(., na.rm = TRUE),
                    p75 = ~ quantile(., 0.75, na.rm = TRUE),
                    max = ~ max(., na.rm = TRUE)))) %>%
  pivot_longer(
    everything(),
    names_to = c("Asignatura", ".value"),
    names_sep = "_") %>%
  mutate(across(-Asignatura, ~ round(., 2)))
```


## Representación de la Relación con ggpairs

```{r}
ggpairs(estadisticos %>% select(-Asignatura))

```


## Matrices de Correlación y Convarianza

```{r}
vars <- notas %>% select(ANM, ALG, MD, FP, DCS)

cor_pearson <- cor(vars, use = "pairwise.complete.obs", method = "pearson")

cor_spearman <- cor(vars, use = "pairwise.complete.obs", method = "spearman")

cor_pearson
cor_spearman

covarianza <- cov(vars, use = "pairwise.complete.obs")
covarianza
```
*Los pares de variables con relaciones más altas son ALG con ANM con un 0,57 aproximadamente, seguido por FP y ALG con un 0,56 aproximadamente*


## Representación de Boxplots

```{r}
notas %>%
  pivot_longer(
    cols = c(ANM, ALG, MD, FP, DCS),
    names_to = "Asignatura",
    values_to = "Nota"
  ) %>%
  ggplot(aes(x = Asignatura, y = Nota, fill = Asignatura)) +
  geom_boxplot() +
  theme_minimal() +
  labs(
    title = "Distribución de calificaciones por asignatura",
    x = "Asignatura",
    y = "Calificación"
  ) +
  theme(legend.position = "none")
```




